name: Build ZMK firmware
on:
  workflow_dispatch:  # can be triggered manually
  push:               # automatically run on changes to following paths
    paths:
      - ".github/workflows/build-k03.yml"
      - "config/k03_ruen.keymap"
      - "config/k03.json"
      # - 'boards/*/*/*.keymap'

jobs:
  build:
    uses: ergohaven/ergohaven-zmk/.github/workflows/build-user-config.yml@main
