# Example for using the keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch:  # can be triggered manually
  push:               # automatically run on changes to following paths
    paths:
      - "config/k03_ruen.keymap"
      - "config/k03.json"
      # - "config/*.dtsi"
      - "keymap-drawer/config.yaml"
      # - 'boards/*/*/*.keymap'
      - ".github/workflows/draw-keymaps.yml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write  # allow workflow to commit to the repo
    with:
      keymap_patterns: "config/k03_ruen.keymap"        # path to the keymaps to parse
      config_path: "keymap-drawer/config.yaml"  # config file, ignored if not exists
      json_path: config/
      output_folder: "keymap-drawer"            # path to save produced SVG and keymap YAML files
      # install_branch: main
      # amend_commit: true
      parse_args: ""  # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      # draw_args: "--physical-layout keymap-drawer/k03_layout.yaml"
      # draw_args: "hummingbird:'-k rufous -g 0 9 26 29'"
      # draw_args: ""   # map of extra args to pass to `keymap draw`, e.g. "corne:'-k corne_rotated' cradio:'-k paroxysm'"
